# -*- coding: utf-8 -*-
"""
Created on Sun Jan  3 10:22:39 2021

@author: Benjamin
"""

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import numpy as np

Fibo = np.array([0,1])

while Fibo.max() < 4000000:
    N = (Fibo.max() + Fibo[len(Fibo)-2])
    Fibo = np.append(Fibo, N)

Fibo = np.delete(Fibo, len(Fibo)-1)

evens = Fibo[range(0, len(Fibo), 3)]

Answer = sum(evens)
print(Answer)

